version: "3.7"
services:
  client:
    image: inspectorr/mml-client:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: client
    depends_on:
      - api
    ports:
      - "127.0.0.1:3001:3001"
  api:
    image: inspectorr/mml-api:latest
    restart: always
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: api
    ports:
      - "127.0.0.1:3000:3000"
