version: "3.7"
services:
  client:
    image: inspectorr/mml-client:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: client
    depends_on:
      - api
    ports:
      - "3001:3001"
  api:
    image: inspectorr/mml-api:latest
    restart: always
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: api
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    links:
      - client:client
      - api:api
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
